=== AlixMeng/open-lims/templates/OLDL/oldl.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT OLDL (HEAD?,REQUIRED?,BODY?)>

<!ELEMENT HEAD (ID|TITLE|VERSION?|AUTHOR?|DESC?|LOCATION?|MANUFACTURER?|EXPIRY?)*>
<!ELEMENT REQUIRED (ITEM*,CLASS*)>
<!ELEMENT BODY (ITEM|CLASS|STATUS|EXTENSION|QUALITYCHECK?)*>

<!ELEMENT STATUS (ITEM|ITEMI|CLASS|ANALYSIS|QUALITYCHECK?)*>

<!ELEMENT ITEM (TYPE|INFORMATION|CATEGORY|ITEM)*>
<!ELEMENT ITEMI EMPTY>

<!ELEMENT CLASS (INFORMATION)*>

<!ELEMENT INFORMATION EMPTY>

<!ELEMENT TYPE EMPTY>
<!ELEMENT CATEGORY EMPTY>

<!ELEMENT ANALYSIS (COMPARE|MODULE|EXTENSION)>

<!ELEMENT COMPARE (FILTER)>
<!ELEMENT MODULE (FILTER)>
<!ELEMENT EXTENSION (FILTER)>

<!ELEMENT FILTER EMPTY>

<!ELEMENT QUALITYCHECK EMPTY>

<!ELEMENT ID (#PCDATA)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT VERSION (#PCDATA)>
<!ELEMENT AUTHOR (#PCDATA)>
<!ELEMENT DESC (#PCDATA)>
<!ELEMENT LOCATION EMPTY>
<!ELEMENT MANUFACTURER EMPTY>
<!ELEMENT EXPIRY EMPTY>

<!ATTLIST 	OLDL
	type			CDATA						#IMPLIED
>	

<!ATTLIST 	STATUS
	id				CDATA						#REQUIRED
	requirement		(force|optional)    		#IMPLIED
>        

<!ATTLIST 	ITEM
	type	        CDATA    									#IMPLIED
	classify	    (force|optional|forbidden)					#IMPLIED
	occurrence		(once|multiple|update-once|update-multiple)	#IMPLIED      
	requirement		(force|optional)							#IMPLIED   
	class			CDATA										#IMPLIED      
	name			CDATA										#IMPLIED      
	gid				CDATA										#IMPLIED
	folder			CDATA										#IMPLIED
	inherit			(all|true|false)							#IMPLIED
>       

<!ATTLIST 	ITEMI
	parent			CDATA										#REQUIRED
	classify	    (force|optional|forbidden)					#IMPLIED
	occurrence		(once|multiple|update-once|update-multiple)	#IMPLIED      
	requirement		(force|optional)							#IMPLIED   
	class			CDATA										#IMPLIED      
	name			CDATA										#IMPLIED      
	gid				CDATA										#IMPLIED
	folder			CDATA										#IMPLIED	
>      

<!ATTLIST 	TYPE
	id				CDATA						#REQUIRED
>	

<!ATTLIST 	CATEGORY
	id				CDATA						#REQUIRED
>	

<!ATTLIST 	CLASS
	name			CDATA						#REQUIRED
>
      
<!ATTLIST 	INFORMATION
	keywords		(keywords)					#IMPLIED	
	description		(description)				#IMPLIED
>	

<!ATTLIST 	ANALYSIS
	requirement		(force|optional)			#IMPLIED
	occurrence		(once|multiple)				#IMPLIED      
>
       
<!ATTLIST 	COMPARE
	name			CDATA						#REQUIRED
>      
       
<!ATTLIST 	MODULE
	name			CDATA						#REQUIRED
	funciton		CDATA						#REQUIRED
>

<!ATTLIST 	EXTENSION
	identifer		CDATA						#REQUIRED
>

<!ATTLIST 	FILTER
	status			CDATA						#REQUIRED
	type			CDATA						#IMPLIED
>

<!ATTLIST 	LOCATION
	requirement		(force|optional)			#IMPLIED
>

<!ATTLIST 	MANUFACTURER
	requirement		(force|optional)			#IMPLIED
>

<!ATTLIST 	EXPIRY
	requirement		(force|optional)			#IMPLIED
>

=== AlixMeng/open-lims/templates/OLDL/sample_general_w_expiry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL type="sample">
	<HEAD>
		<ID>101</ID>
	 	<TITLE>General w. Location</TITLE>
		<DESC>General Sample Template</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR></AUTHOR>
		<LOCATION requirement="optional"> />
		<MANUFACTURER requirement="optional"> />
		<EXPIRY />
	</HEAD>
	<BODY>
      <ITEM type="value">       
            <TYPE id="100"></TYPE>
      </ITEM>      
	</BODY>
</OLDL>

=== AlixMeng/open-lims/templates/OLDL/sample_rna_w_manufacturer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL type="sample">
	<HEAD>
		<ID>10002</ID>
	 	<TITLE>RNA w. Manufacturer</TITLE>
		<DESC>Organisational RNA Template</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR></AUTHOR>
		<MANUFACTURER />
	</HEAD>
	<BODY>
	</BODY>
</OLDL>

=== AlixMeng/open-lims/templates/OLDL/sample_rna.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL type="sample">
	<HEAD>
		<ID>10000</ID>
	 	<TITLE>RNA</TITLE>
		<DESC>Organisational RNA Template</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR></AUTHOR>
	</HEAD>
	<BODY>
	</BODY>
</OLDL>

=== AlixMeng/open-lims/templates/OLDL/sample_microarray_w_location.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL type="sample">
	<HEAD>
		<ID>11001</ID>
	 	<TITLE>MicroArray</TITLE>
		<DESC>Organisational Microarray Template</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR></AUTHOR>
		<LOCATION />
	</HEAD>
  	<REQUIRED>  
     	<ITEM type="parentsample"></ITEM>            
      	<ITEM type="parentsample"></ITEM>
  	</REQUIRED>
	<BODY>
	</BODY>
</OLDL>

=== AlixMeng/open-lims/templates/OLDL/sample_rna_w_manufacturer_and_location.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL type="sample">
	<HEAD>
		<ID>10003</ID>
	 	<TITLE>RNA w. Manufacturer and Location</TITLE>
		<DESC>Organisational RNA Template</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR></AUTHOR>
		<LOCATION />
		<MANUFACTURER />
		<EXPIRY />
	</HEAD>
	<BODY>
	</BODY>
</OLDL>

=== AlixMeng/open-lims/templates/OLDL/project_microarray_standard.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL>
	<HEAD>
		<ID>10001</ID>
	 	<TITLE>MicroArray - Standard</TITLE>
		<DESC>Standard-Template for MicroArray based Projects</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR>The Open-LIMS Project</AUTHOR>
	</HEAD>
	<REQUIRED>
		<ITEM type="value">
          <TYPE id="10000"></TYPE>
    </ITEM>
	</REQUIRED>
	<BODY>
		<STATUS id="1">
			<ITEM type="sample" occurrence="multiple">
            	<TYPE id="10000"></TYPE>
     		</ITEM>
		</STATUS>
		<STATUS id="10001">
			<ITEM type="value" id="10001">
          		  <TYPE id="10001"></TYPE>
      		</ITEM>   
			<ITEM type="file" occurrence="multiple" requirement="optional" name="Add BioAnalyzer File"></ITEM>    
			<ITEM type="equipment" occurrence="multiple"></ITEM>       
		</STATUS>
		<STATUS id="10002">
  			<ITEM type="sample" occurrence="multiple">
         		<TYPE id="11000"></TYPE>
    		</ITEM>		
		</STATUS>
		<STATUS id="10003">
			<ITEM type="value" id="10003">
         		<TYPE id="10003"></TYPE>
      		</ITEM>
			<ITEM type="equipment" occurrence="multiple"></ITEM>
		</STATUS>
		<STATUS id="10004">
			<ITEM type="equipment" occurrence="multiple"></ITEM>
		</STATUS>
		<STATUS id="10005">
			<ITEM type="equipment" occurrence="multiple"></ITEM>
		</STATUS>
		<STATUS id="10006">
		  	<ITEM type="file"></ITEM>
			<ITEM type="equipment" occurrence="multiple"></ITEM>
		</STATUS>
		<STATUS id="10007">
			<ITEM type="equipment" occurrence="multiple"></ITEM>
		</STATUS>
		<STATUS id="10008">
			<ITEM type="file" occurrence="multiple"></ITEM>
		</STATUS>
		<STATUS id="10009">
			<EXTENSION internal_name="marray_analysis" />
			<ITEM type="file" occurrence="multiple" name="Add SAM Result"></ITEM>
		</STATUS>
	</BODY>
</OLDL>

=== AlixMeng/open-lims/templates/OLDL/sample_rna_w_location.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL type="sample">
	<HEAD>
		<ID>10001</ID>
	 	<TITLE>RNA w. Location</TITLE>
		<DESC>Organisational RNA Template</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR></AUTHOR>
		<LOCATION />
		<EXPIRY />
	</HEAD>
	<BODY>
	</BODY>
</OLDL>

=== AlixMeng/open-lims/templates/OLDL/sample_rna_w_expiry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL type="sample">
	<HEAD>
		<ID>10001</ID>
	 	<TITLE>RNA w. Date of Expiry</TITLE>
		<DESC>Organisational RNA Template</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR></AUTHOR>
		<LOCATION requirement="optional" />
		<MANUFACTURER requirement="optional" />
		<EXPIRY />
	</HEAD>
	<BODY>
	</BODY>
</OLDL>
