=== AlixMeng/open-lims/templates/OLDL/oldl.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT OLDL (HEAD?,REQUIRED?,BODY?)>

<!ELEMENT HEAD (ID|TITLE|VERSION?|AUTHOR?|DESC?|LOCATION?|MANUFACTURER?|EXPIRY?)*>
<!ELEMENT REQUIRED (ITEM*,CLASS*)>
<!ELEMENT BODY (ITEM|CLASS|STATUS|EXTENSION|QUALITYCHECK?)*>

<!ELEMENT STATUS (ITEM|ITEMI|CLASS|ANALYSIS|QUALITYCHECK?)*>

<!ELEMENT ITEM (TYPE|INFORMATION|CATEGORY|ITEM)*>
<!ELEMENT ITEMI EMPTY>

<!ELEMENT CLASS (INFORMATION)*>

<!ELEMENT INFORMATION EMPTY>

<!ELEMENT TYPE EMPTY>
<!ELEMENT CATEGORY EMPTY>

<!ELEMENT ANALYSIS (COMPARE|MODULE|EXTENSION)>

<!ELEMENT COMPARE (FILTER)>
<!ELEMENT MODULE (FILTER)>
<!ELEMENT EXTENSION (FILTER)>

<!ELEMENT FILTER EMPTY>

<!ELEMENT QUALITYCHECK EMPTY>

<!ELEMENT ID (#PCDATA)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT VERSION (#PCDATA)>
<!ELEMENT AUTHOR (#PCDATA)>
<!ELEMENT DESC (#PCDATA)>
<!ELEMENT LOCATION EMPTY>
<!ELEMENT MANUFACTURER EMPTY>
<!ELEMENT EXPIRY EMPTY>

<!ATTLIST 	OLDL
	type			CDATA						#IMPLIED
>	

<!ATTLIST 	STATUS
	id				CDATA						#REQUIRED
	requirement		(force|optional)    		#IMPLIED
>        

<!ATTLIST 	ITEM
	type	        CDATA    									#IMPLIED
	classify	    (force|optional|forbidden)					#IMPLIED
	occurrence		(once|multiple|update-once|update-multiple)	#IMPLIED      
	requirement		(force|optional)							#IMPLIED   
	class			CDATA										#IMPLIED      
	name			CDATA										#IMPLIED      
	gid				CDATA										#IMPLIED
	folder			CDATA										#IMPLIED
	inherit			(all|true|false)							#IMPLIED
>       

<!ATTLIST 	ITEMI
	parent			CDATA										#REQUIRED
	classify	    (force|optional|forbidden)					#IMPLIED
	occurrence		(once|multiple|update-once|update-multiple)	#IMPLIED      
	requirement		(force|optional)							#IMPLIED   
	class			CDATA										#IMPLIED      
	name			CDATA										#IMPLIED      
	gid				CDATA										#IMPLIED
	folder			CDATA										#IMPLIED	
>      

<!ATTLIST 	TYPE
	id				CDATA						#REQUIRED
>	

<!ATTLIST 	CATEGORY
	id				CDATA						#REQUIRED
>	

<!ATTLIST 	CLASS
	name			CDATA						#REQUIRED
>
      
<!ATTLIST 	INFORMATION
	keywords		(keywords)					#IMPLIED	
	description		(description)				#IMPLIED
>	

<!ATTLIST 	ANALYSIS
	requirement		(force|optional)			#IMPLIED
	occurrence		(once|multiple)				#IMPLIED      
>
       
<!ATTLIST 	COMPARE
	name			CDATA						#REQUIRED
>      
       
<!ATTLIST 	MODULE
	name			CDATA						#REQUIRED
	funciton		CDATA						#REQUIRED
>

<!ATTLIST 	EXTENSION
	identifer		CDATA						#REQUIRED
>

<!ATTLIST 	FILTER
	status			CDATA						#REQUIRED
	type			CDATA						#IMPLIED
>

<!ATTLIST 	LOCATION
	requirement		(force|optional)			#IMPLIED
>

<!ATTLIST 	MANUFACTURER
	requirement		(force|optional)			#IMPLIED
>

<!ATTLIST 	EXPIRY
	requirement		(force|optional)			#IMPLIED
>

=== AlixMeng/open-lims/templates/OLDL/project_microarray_parent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL>
	<HEAD>
		<ID>19000</ID>
		<TITLE>MicroArray - Parent Project</TITLE>
		<DESC>Parent Project for different Microarray projects</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR></AUTHOR>
	</HEAD>
	<REQUIRED>  
  	</REQUIRED>
	<BODY>
		<STATUS id="10001"></STATUS>
		<STATUS id="10002"></STATUS>
		<STATUS id="10003"></STATUS>
		<STATUS id="10004"></STATUS>
		<STATUS id="10005"></STATUS>
		<STATUS id="10006"></STATUS>
		<STATUS id="10007"></STATUS>
		<STATUS id="10008"></STATUS>
		<STATUS id="10009"></STATUS>
	</BODY>
</OLDL>

=== AlixMeng/open-lims/templates/OLDL/sample_microscopy_live_imaging.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL type="sample">
	<HEAD>
		<ID>20020</ID>
	 	<TITLE>Microscopy - Live Imaging</TITLE>
		<DESC>Template for live imaging microscopy</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR></AUTHOR>
	</HEAD>
	<BODY>
      <ITEM type="value">        
            <TYPE id="20103"></TYPE>
      </ITEM>      
      <ITEM type="equipment" name="Add Used Hardware" occurrence="multiple">
           <TYPE id="3"></TYPE>
           <CATEGORY id="1003"></CATEGORY>              
           <CATEGORY id="1007"></CATEGORY>
      </ITEM>       
      <ITEM type="equipment" name="Add Used Software" occurrence="multiple">
           <TYPE id="3"></TYPE>
           <CATEGORY id="1008"></CATEGORY>
      </ITEM>         
      <ITEM type="file" name="Add Main/RAW File" folder="main" occurrence="multiple"></ITEM>
      <ITEM type="file" name="Add Shortlist RAW File" folder="shortlist raw" requirement="optional" occurrence="multiple"></ITEM>        
      <ITEM type="file" name="Add TIF File" folder="tif" requirement="optional" occurrence="multiple"></ITEM>      
      <ITEM type="file" name="Add Configuration File" folder="tif" requirement="optional" occurrence="multiple"></ITEM>  
      <ITEM type="parentsample" requirement="optional" occurrence="multiple"></ITEM>         
      <ITEM type="value" requirement="optional">        
           <TYPE id="20001"></TYPE>
      </ITEM> 
	</BODY>
</OLDL>
